#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE $KEYCLOAK_DB;
    GRANT ALL PRIVILEGES ON DATABASE $KEYCLOAK_DB TO $POSTGRES_USER;
EOSQL
